### ISSUE TITLE
Fatal error while generating with --gen-obj option

### ISSUE THREAD

**Issue by elhaddadyacine** [rlepigre/lambdapi#107]
I have an error while generating the object file.
The file `proof_trace.lp` is checked by `lambdapi` but it return a fatal error when I use the `--gen-obj`option (and generate an empty `.lpo` file)
All files needed are attached in this issue.

Error message :

> Fatal error: exception File "src/sign.ml", line 135, characters 22-28: Assertion failed
Checked [proof_trace.lp]

[trace.zip](https://github.com/rlepigre/lambdapi/files/2541390/trace.zip)

**Comment by rlepigre** [comment]
I'm guessing that some metavariable could not be instantiated. Could you send me a self-contained examples? Files are missing in the archive (nothing in the `logic` and `lemmas` folders).

**Comment by rlepigre** [comment]
Try again with the latest version, be6d0c53c7614237cbf97711edd4660b411251c4 should have fixed the problem (if my guess was correct). You should now get an error message earlier, telling you where the problem is.

**Comment by rlepigre** [comment]
OK, now you have a good error message with 27455a9044c25de1fc50c067d44fda5d08332260. This should have been done long ago.

Note that this reveals a slight problem in the way we check constraints during type-checking. I will open a fresh issue for that.

**Comment by rlepigre** [comment]
I don't know if this is obvious, but a fix for you now is to add type annotations on lambdas where `lambdapi` is unable to guess the type. We will try to ensure that proper instantiation is done to avoid having to give such annotations as soon as possible.

**Comment by elhaddadyacine** [comment]
Thank you, i'll try to fix the generated proofs but I still have some proofs which contains lambdas without type annotation and typecheck correctly (I guess that lambdapi found the right type annotation for each lambda).
