### ISSUE TITLE
Optimise the construction of reduction rules

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/lambdapi#11]
We should consider variables that are unused in the RHS as being wildcards.

**Comment by francoisthire** [comment]
What about :

Eq x x --> true

?

Le 25 janv. 2018 1:14 PM, "Rodolphe Lepigre" <notifications@github.com> a
écrit :

**Comment by rlepigre** [comment]
Well, I meant variables that appear only once.

**Comment by fblanqui** [comment]
Another optimisation to do in Eval.find_rule:

The following data:

    let env = Array.init (Bindlib.mbinder_arity r.lhs) (fun i -> ITag(i)) in
    let lhs = Bindlib.msubst r.lhs env in
    Bindlib.msubst r.rhs env

should be computed only once when the rule is created.

**Comment by rlepigre** [comment]
Yes, I was planing to do that.

**Comment by rlepigre** [comment]
This has been fixed in branch `pa`.
