### ISSUE TITLE
Compilation failed because of Earley

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/lambdapi#117]
On Master, after a `git pull` I use `make` and it fails with the following error message

```
File "src/dune", line 7, characters 31-42:
7 |  (libraries unix timed bindlib earley.core))
                                   ^^^^^^^^^^^
Error: Library "earley.core" not found.
Hint: try: dune external-lib-deps --missing @@default
GNUmakefile:11: recipe for target 'bin' failed
make: *** [bin] Error 1
```

Earley is installed via opam and I am using version 1.1.0 of earley and earley-ocaml. My version of OCaml is 4.04.2 .

**Comment by rlepigre** [comment]
If you look at `README.md`, you'll see that `lambdapi` now requires `earley.2.0.0`. Note that `earley-ocaml` and `earley` are only a single `opam` package from this version up.

**Comment by francoisthire** [comment]
Then update lambdapi.opam also.

Le sam. 17 nov. 2018 à 17:46, Rodolphe Lepigre <notifications@github.com> a
écrit :

**Comment by rlepigre** [comment]
I knew I did that, but I forgot to push...
