### ISSUE TITLE
Require command behavior

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/lambdapi#118]
I have the three following files

## cic.dk

```
Sort : Type.

def Rule : Sort -> Sort -> Sort -> Type.

True : Type.
```

## test_univ.dk

```
#REQUIRE cic.dk

def ?1 : cic.Sort.

def ?2 : cic.Sort.

def ?3 : cic.Sort.
```

## oops.dk
```
#REQUIRE cic.
#REQUIRE test_univ.

[] cic.Rule test_univ.?1 test_univ.?2 test_univ.?3 --> cic.True.
```

As they are presented now, everything is fine if one runs the following command
```
lamdapi oops.dk
```

However, I observe two strange behaviors. The first one is that everything is fine also if one removes the require command in `test_univ.dk`, but of course if the two require commands of `oops.dk` are permuted, then it fails this time : 

```
[test_univ.dk, 3:9-17] No module [cic] loaded.
```

I am not sure that this behavior is intented.

The other one is that if this time, we remove the require command for the cic module in `oops.dk` then we get an uncaught exception : 

```
Checked [test_univ.dk]
[bouh.dk, 3:0-64] Uncaught exception [File "src/sign.ml", line 203, characters 24-30: Assertion failed].
```

**Comment by rlepigre** [comment]
This is a scoping bug. Of course, this behavior was not intended. I introduced this bug when I added the `open` statement and related stuff. Thanks for the report!
