### ISSUE TITLE
Zenon library needs too much disk space for testing

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/lambdapi#16]
We should ask the maintainer of the library to pack the source files differently. I propos a `.tar` archive with `.dk.gz` files inside. This only takes a small amount of extra space and allow us to work on file independently. The problem is, it is not possible to extract a single file (efficiently) from a `.tar.gz` archive.

**Comment by fblanqui** [comment]
@rlepigre : shouldn't we close this issue?

**Comment by rlepigre** [comment]
Yes, we can close it now!
