### ISSUE TITLE
Typecheck with CoC option

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/lambdapi#17]
Is this feature essential? What does it imply for the theory, besides the new rule for product types?

**Comment by fblanqui** [comment]
Ask on dedukti-dev.


Le 02/02/2018 à 10:53, Rodolphe Lepigre a écrit :

**Comment by francoisthire** [comment]
Clearly it is not essential. This option allows adding Kind objects inside
the typing context, allowing some polymorphism. However, this option does
not extend for typing rewrite rules, or at least not in an proper way.

2018-02-02 11:11 GMT+01:00 Frédéric Blanqui <notifications@github.com>:

**Comment by fblanqui** [comment]
There is no need to implement this for the moment.
