### ISSUE TITLE
Separate the code for type-checking from the code for subject reduction

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#19]
Wouldn't be better, for the moment, to separate the code for type-checking from the code for subject reduction, even though subject reduction shares many things with type-checking? I think that it would be cleaner and would allow one to modify the code for type-checking independently of subject reduction, and vice versa. Type checking should fail when a unification variable is encountered. Subject reduction should be developed in a separate file say sr.ml.

**Comment by rlepigre** [comment]
What should we do about this issue? Do you consider it fixed now?

**Comment by fblanqui** [comment]
It is indeed done. The only thing is that, currently, because abstractions with no type annotation are accepted, type-checking must not fail when called on a unification variable. So it was wrong to require type-checking to fail in this case.

**Comment by fblanqui** [comment]
For the record, it was done in commit 8e55568.
