### ISSUE TITLE
Do we want to type-check in #EVAL command?

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/lambdapi#23]
https://github.com/rlepigre/lambdapi/blob/561b959f55ebc8ce397dd6a433964f1b214f7de8/src/handle.ml#L70-L73

Do we want to be able to reduce ill-typed terms or not?

For now, we do not type-check before evaluating.

**Comment by francoisthire** [comment]
Well, it might be a feature that you can reduce ill-typed terms with the `eval` command but the only case I had to reduce ill-typed terms was while I was using Dedukti with an API.

However, while using the command `eval` I prefer that the default behavior type check the term first.
