### ISSUE TITLE
Remove dependency on compiler evaluation order?

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#25]
https://github.com/rlepigre/lambdapi/blob/bd4589f4c1fb94dae951a4b8d8703a27c501730a/src/extra.ml#L53

Is it part of OCaml specification?

**Comment by rlepigre** [comment]
I thought it was, but it is actually specified as unspecified. This has been fixed in f67e1feab264ace97ca714833217ebcec50df5f6.
