### ISSUE TITLE
Comment required on the use of # for naming wildcard variables

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#26]
https://github.com/rlepigre/lambdapi/blob/ebfea320770e59506617753633f93bee989079db/src/scope.ml#L103

I guess that yo use # because no identifier is allowed to start with #.

But why do you need to give a name to wildcard variables at all?

Some comment is needed here.

**Comment by rlepigre** [comment]
Done in 81297af95ce45d9f2cdfe9bae3a6ff4e333c7385.
