### ISSUE TITLE
Difference between P_Def and P_NewDef or P_NewSym?

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#27]
https://github.com/rlepigre/lambdapi/blob/b38df214567355baf7f481617a0ce8c85a45c2a8/src/parser.ml#L105

Comment required.

**Comment by rlepigre** [comment]
`P_NewDef` and `P_NewSym` correspond to (definable or static) symbol declarations only. This means that in the case of a definable symbol, it is not given any reduction rule.

On the contrary, the `P_Def` constructor declares a new definable symbol with an immediate reduction rule. It corresponds to the syntax `def f : A := t`.
