### ISSUE TITLE
Line number missing in some error messages

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#29]
For instance here:

https://github.com/rlepigre/lambdapi/blob/2258c46dd85ea119b12b91083ffb718296c96fd3/src/scope.ml#L30

**Comment by fblanqui** [comment]
To do this in type inference or type checking, we would need terms to carry some information about positions...

**Comment by fblanqui** [comment]
Without that, it should at least be possible to output the current position of the parser. It won't allow us to point to a precise position in a term but, at least, help the user to now in which command there is a problem.

**Comment by fblanqui** [comment]
In error messages, the position (file name, line and character numbers) should appear first.

**Comment by fblanqui** [comment]
@rlepigre : shouldn't we close this issue?

**Comment by rlepigre** [comment]
Yes, let's close it. But we should open other ones if we find messages that are not satisfactory (or have no line number and should have one).
