### ISSUE TITLE
add a parser for module names?

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#31]
https://github.com/rlepigre/lambdapi/blob/821a972add8c4075ed7eced7d9951a84b129e2f4/src/parser.ml#L43

Why not let the parser do the splitting itself by adding a parser for module names?

And module names will be useful when we will add some Require command.

**Comment by rlepigre** [comment]
The reason for using Earley's regular expressions is that it is more efficient than a parsing rule (there is an ambiguity in the parser due to the final dots).

What do you mean about a require command? There already is one!

**Comment by fblanqui** [comment]
Le 22/03/2018 à 08:29, Rodolphe Lepigre a écrit :
>
> The reason for using Earley's regular expressions is that it is more 
> efficient than a parsing rule (there is an ambiguity in the parser due 
> to the final dots).
>
Ok, I understand. Could you please add a comment in the code about that?

> What do you mean about a require command? There already is one!
>
I didn't know. Good! :-)

**Comment by rlepigre** [comment]
> Barrette femelle (standard) econ connect

Done in 06960d7b2c07bbbeae0474da3894d69cecc1d9a6.
