### ISSUE TITLE
Remove rule environments?

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#33]
To discuss point 2 in #32 .

**Comment by fblanqui** [comment]
Question: can we remove rule environment? That is, write:

add Zero ?m --> ?m.

instead of:

[m] add Zero m --> m.

It seems indeed possible to do this by replacing free variables by metavariables in rules.

**Comment by rlepigre** [comment]
It is possible, off course. See https://github.com/rlepigre/lambdapi/tree/metavar.

**Comment by fblanqui** [comment]
Done in branch pa.
