### ISSUE TITLE
Comment missing on type cmd

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#35]
https://github.com/rlepigre/lambdapi/blob/6c3a72613cc9a91ec1cf02f7fb8fc1c5da407e87/src/cmd.ml#L27

What is the boolean argument for?

**Comment by fblanqui** [comment]
Idem in parser.ml, line 138.

**Comment by rlepigre** [comment]
That's for opaque definitions. I'll correct that.

**Comment by rlepigre** [comment]
Fixed in b047024a978621e71cf034b6978028a6c71bdf05.
