### ISSUE TITLE
Assertion failed on dummy example

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/lambdapi#38]
An assertion failure is raised on the example below:

```
A : Type.

def g : A -> A.

[] g --> x => x.
```

**Comment by fblanqui** [comment]
Added François' example in tests/KO/uninst_meta_in_rhs.dk (commit 82207d4).
The error message is now: "missing type annotation [tests/KO/uninst_meta_in_rhs.dk, 5:14-15]"
