### ISSUE TITLE
Documentation missing about `Func|`Appl|`Atom

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#41]
https://github.com/rlepigre/lambdapi/blob/a3dc67d0655b2337e16481898a0999c0501f213f/src/parser.ml#L117

**Comment by rlepigre** [comment]
Is it really necessary to add something here? It is quite clear that `p` corresponds to a priority level for the parser (see the comment on line 116). What else would you expect here?

**Comment by fblanqui** [comment]
But what is the order on priorities?


Le 02/05/2018 à 10:09, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
Fixed in 14e35804efb05a8ce5eae824226eb9dab28c7ffd.
