### ISSUE TITLE
`initial_state` and `Sign.loading` / `loaded`.

### ISSUE THREAD

**Issue by ejgallego** [rlepigre/lambdapi#48]
There is a bit of critical state that is outside the `Handle.Pure` interface; in particular `Sign.loading` and `Sign.loaded`.

I think these should be taken care of in the `Pure` interface, maybe modifying `initial_state` to be:
```ocaml
    val initial_state : module_path -> state
```
so that we can create scoped states for each document that we are processing.

**Comment by rlepigre** [comment]
For now the global state is not correctly handled at all, since we do not update all the references using the Timed module. I'll try fixing all this soon.

**Comment by ejgallego** [comment]
Cool thanks; indeed I didn't find a proper way to make backtracking work reliably.

**Comment by ejgallego** [comment]
In fact the absolutely best thing for us would be to have an interface that takes a `type document` for all operations, as it is done in Coq these days.

It is very common that the language server wants to handle two `.dk` files at the same time, so for example we are going to have:
```
d1 d2 : document
```
and the server wants to often do `check d1 s1; check d2 s2;`, etc...

**Comment by rlepigre** [comment]
OK, what would `document` need to be here? A signature?

**Comment by ejgallego** [comment]
@rlepigre I think so, a document is basically something that will be mapped to a file.

So for example the user could compile it. It'd be great if LP could work with several open documents and this would allow a much better IDE integration.

I guess the exact notion depends on how you map signatures to files.

**Comment by rlepigre** [comment]
OK, I'll try to implement that before the end of the week. Actually, I've already started in the `withstate` branch, but it still requires some work. The current version mixes functional and imperative state, so don't try it yet!

**Comment by ejgallego** [comment]
Thanks @rlepigre , that would really help a lot the language server.

**Comment by rlepigre** [comment]
OK @ejgallego, I think that what I did in the `pureinterface` branch should do the trick. Note that moved the `Pure` module to a separate file, and that I produce library files (`.cma`, `.cmxa` and `.cmxs`). Can you try it?

**Comment by ejgallego** [comment]
Great thanks! Will try tonight.

**Comment by ejgallego** [comment]
Ok, so I have pushed a new version to OPAM. Note that we use Dune as a build system so we produce our own packed libraries out of the source tree so we cannot try the `.cmxa` files easily.

It seems that some problems persist, I didn't have time to see if the problem is on our end but what we are doing seems pretty straighforward. @lachhebo can update you on that.

Also, we need to use `current_theorem` for each particular document span; this is not possible to do with the current API.

I'm afraid that an imperative style is gonna be at odds with modern IDE support.

**Comment by rlepigre** [comment]
Well, there is not much I can do on the imperative side right now due to the global handling of metavariables. However, this should change soon, and then we should be able to expose some state.

I'll have a look with @lachhebo to see what's going on later to try to fix the current version.

**Comment by ejgallego** [comment]
Thanks @rlepigre , I am not sure `Pure` is properly restoring the signature, but it is hard to track. I guess that in order to have a bit more of robustness you could allow registering variables with `Timed` [such as `Proofs.theorem`] and not exposing them directly.

This way accidental modification would be prevented.

**Comment by rlepigre** [comment]
Closing this now, #56 has been merged.

**Comment by ejgallego** [comment]
Thanks!!
