### ISSUE TITLE
Useless exception handling?

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#51]
Aren't the following exception handlings useless?

https://github.com/rlepigre/lambdapi/blob/4cef6e2202816ca0c5a289fae511bc771a1a0f4c/src/handle.ml#L202
https://github.com/rlepigre/lambdapi/blob/4cef6e2202816ca0c5a289fae511bc771a1a0f4c/src/handle.ml#L232

If so, we can remove the function handle_cmds completely.

I tested: make tests work well if we remove this code.

**Comment by fblanqui** [comment]
https://github.com/rlepigre/lambdapi/blob/4cef6e2202816ca0c5a289fae511bc771a1a0f4c/src/handle.ml#L174

can raise errors. So it should be included in the try.

**Comment by fblanqui** [comment]
Note that the current version prints no error message:

12:48 ~/lambdapi-git/libraries/dklib ../../lambdapi.native dklib.dk 
Checked [cc.dk]
Checked [dk_bool.dk]
12:49 ~/lambdapi-git/libraries/dklib echo $?
1

**Comment by rlepigre** [comment]
This code should not be removed. If anything it is not harmful, and the `abort` is required to the failure of the program with an error message. In other words, the `Fatal` exception should not escape, and it must always be captured.

For the parsing part, I need to have a better look, but I'm guessing that it is useful as well. However, we should call abort and forward the message. This is done in 088fa1e5c49beb66407ff7f1976a321b04c4cb44.
