### ISSUE TITLE
make dklib fails

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#52]
12:28 ~/lambdapi-git make dklib
\#\# Compiling the dklib library \#\#
Checked [cc.dk]
Checked [dk_bool.dk]
Fatal error: exception Console.Fatal("[dklib.dk, 1:0-23] error while handling a command.\n[dk_machine_int.dk, 3:0-15] error while handling a command.\n[dk_nat.dk, 3:0-16] error while handling a command.\n[dk_list.dk, 3:0-17] error while handling a command.\n[dk_logic.dk, 3:0-16] error while handling a command.\nParse error at [dk_type.dk, 53:15].\n\n\n\n\n\n")
Raised at file "format.ml" (inlined), line 242, characters 35-52
Called from file "format.ml", line 469, characters 8-33
Called from file "format.ml", line 484, characters 6-24
Command exited with non-zero status 2
Finished in 0:00.11 at 98% with 8620Kb of RAM
GNUmakefile:98 : la recette pour la cible « dklib » a échouée
make: *** [dklib] Erreur 2

line in dk_type.dk:

left (A : cc.uT) (B : cc.uT) : cc.eT A -> Sum A B.

Can arguments be given before type declaration?

**Comment by rlepigre** [comment]
Not anymore, I think. But the changes have not be merged upstream I guess. I'll have a look.

**Comment by rlepigre** [comment]
Fixed by 5a009b60b056fcf212a8c103c05b9e21bfc7d07f.

Awaiting PR https://github.com/rafoo/dklib/pull/6 to switch back to main `dklib` repository for testing.
