### ISSUE TITLE
Strange behavior of typing with definable symbols

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/lambdapi#54]
On the following example, lambdapi is happy (I tried to minimize the example):

```
Sort : Type.

succ : Sort -> Sort.

def max : Sort -> Sort -> Sort.
[s1,s2,s3] max (max s1 s2) s3 --> max s1 (max s2 s3).

Univ : Sort -> Type.
def Term : s : Sort -> a : Univ s -> Type.

univ : s : Sort -> Univ (succ s).
def join : s1 : Sort -> s2 : Sort -> Univ s1 -> Univ s2 -> Univ (max s1 s2).
def cast : s1 : Sort -> s2 : Sort -> a : Univ s1 -> b : Univ s2 -> Term s1 a -> Term (max s1 s2) (join s1 s2 a b).

(; [s] Term _ (univ s) --> Univ s. ;)

[s1,s2,s3,t1,t2,t3]
    join _ s3 (join s1 s2 t1 t2) t3 -->
    join s1 (max s2 s3) t1 (join s2 s3 t2 t3).

[s1,s2,s3,t1,t2,t3,a]
    cast _ s3 _ t3 (cast s1 s2 t1 t2 a)
--> cast s1 (max s2 s3) t1 (join s2 s3 t2 t3) a.
```

However, if you uncomment the rewrite rule on `Term`, lambdapi does not typecheck anymore (because of the last rule). But if put this rule at the end of the file, it typechecks again.

I suspect that even if the symbol `Term` is declared as definable, if there is no rewrite rule on this symbol, he is considered as injective. Using the injectivity of `Term` allows the type checker to infer that for the last rule, the second wildcard must be a `join` applied to some arguments, hence, the first wildcard has to be a `max`.

I don't know if this behavior is wanted or not. By the way, Dedukti does not type check the last rule in any way (except if you put explicitly a `join` instead of the wildcard, but since `join` is definable, I don't want to write it explicitly because I want the rule to match a term that can be convertible to a `join` for this wildcard).

**Comment by rlepigre** [comment]
Yes, this is a deliberate choice. We consider that a definable symbol without any reduction rule is injective. You can see this here:
https://github.com/rlepigre/lambdapi/blob/25b6647e52de89705895b88a5369ded63fed63a4/src/sign.ml#L196-L198

Of course, this choice is subject to discussion.

**Comment by francoisthire** [comment]
I am wondering, however, if this rule should type check even if Term is not injective (with @fblanqui  algorithm maybe?).

**Comment by fblanqui** [comment]
There is no problem for join _ s3 (join s1 s2 t1 t2) t3 --> join s1 (max s2 s3) t1 (join s2 s3 t2 t3) [R1] thanks to the associativity rule on max [R0].

Consider now cast X s3 Y t3 (cast s1 s2 t1 t2 a) --> cast s1 (max s2 s3) t1 (join s2 s3 t2 t3) a [R2].

When the LHS is typable, we have Term X Y = Term (max s1 s2) (join s1 s2 t1 t2) [H1].

For the RHS to have the same type, we need to have Term (max X s3) (join X s3 Y t3) = Term (max s1 (max s2 s3)) (join s1 (max s2 s3) t1 (join s2 s3 t2 t3)) [G].

If Term is injective, which is in particular the case when there is no rule on Term, then we can deduce from [H1] that X = max s1 s2 [H2] and Y = join s1 s2 t1 t2 [H3]. So, to prove that [G] holds, we are left to prove that join (max s1 s2) s3 (join s1 s2 t1 t2) t3 = join s1 (max s2 s3) t1 (join s2 s3 t2 t3), which holds by [R1].

So, [R2] preserves typing as long as Term is injective.

Now, it would be nice to have a criterion for injectivity other than checking the absence of rules!...

If Term is not injective, I see no reason why [H2] and [H3] should hold, and thus [G].

**Comment by francoisthire** [comment]
@rafoo had a criterion to check the injectivity of a symbol, i'll try to
find his message.

Le mer. 13 juin 2018 à 17:36, Frédéric Blanqui <notifications@github.com> a
écrit :

**Comment by francoisthire** [comment]
However, the current implementation breaks subject reduction as proved by the following example:
```
Nat : Type.

0 : Nat.
S : Nat -> Nat.

elt : Type.
Vect : Nat -> Type.

Nil : Vect 0.
Cons : n : Nat -> elt -> Vect n -> Vect (S n).

def Tail : n : Nat -> Vect (S n) -> Vect n.
[n, x, l] Tail n (Cons _ x l) --> l.

def S_bis : Nat -> Nat.

Cons_bis : n : Nat -> elt -> Vect n -> Vect (S_bis n).


def Tail_bis : n : Nat -> Vect (S_bis n) -> Vect n.
(; La règle non-linéaire, qui est acceptée pour le typage ;)
[n, x, l] Tail_bis n (Cons_bis n x l) --> l.
(; ;)
(; La règle linéaire, qui pose un problème de préservation du typage ;)
[n, x, l] Tail_bis n (Cons_bis _ x l) --> l.
(; ;)

[]  S_bis 0         --> S (S 0)
[]  S_bis (S 0)     --> S (S 0)
[n] S_bis (S (S n)) --> S (S (S_bis n)).


e : elt.
def 1 := S 0.
def 2 := S 1.
def 3 := S 2.
def suite := Cons 2 e (Cons 1 e (Cons 0 e Nil)).

#CHECK (Tail_bis 2 (Cons_bis 3 e suite)) :: Vect 2.
#CHECK suite :: Vect 3.
#CHECK (Tail_bis 2 (Cons_bis 3 e suite)) == suite.
#CHECK Vect 3 == Vect 2.
```

**Comment by fblanqui** [comment]
These conditions do not seem sufficient. Take f 0 --> 0 and f (s 0) --> 0.


Le 14/06/2018 à 10:43, fthire a écrit :

**Comment by fblanqui** [comment]
As already mentioned, this is a modularity problem. When you add the 
rules on Tail_bis in the environment, they indeed preserve typing. This 
property is not preserved though when you add the rules on S_bis because 
they break the injectivity of S_bis. There is no surprise here. A 
solution could be as follows: we remember that S_bis needs to be 
injective; when rules are added on S_bis, we check that the injectivity 
of S_bis is preserved; if this is not the case, then we reject the rules.


Le 14/06/2018 à 10:40, fthire a écrit :

**Comment by francoisthire** [comment]
Well, but we do not know how to check injectivity yet...
