### ISSUE TITLE
Bug in SR checking

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#65]
The example of https://github.com/Deducteam/Dedukti/pull/66 does not work in Lambdapi either.

```
type : Type.
def term : type -> Type.

eq : A : type -> term A -> term A -> type.
def Eq (A : type) (a : term A) (b : term A) : Type := term (eq A a b).

refl : A : type -> a : term A -> Eq A a a.
sym : A : type -> a : term A -> b : term A -> Eq A a b -> Eq A b a.
def trans : A : type -> a : term A -> b : term A -> c : term A ->
            Eq A a b -> Eq A b c -> Eq A a c.

[A,a,b,h] trans A a b a h (sym A a b h) --> refl A a
[A,a,b,h] trans A b a b (sym A a b h) h --> refl A b
[A,a,b,h] trans A a b b h (refl A b) --> h
[A,a,b,h] trans A a a b (refl A a) h --> h
[A,w,x,y,z,h,h',h''] trans A w x z h (trans A x y z h' h'') -->
  trans A w y z (trans A w x y h h') h''.

def bpi : X : type -> x : term X -> y : term X -> h : Eq X x y ->
          P : (y : term X -> Eq X x y -> type) ->
          term (P x (refl X x)) -> term (P y h).

(; The left-hand side ;)

def bpi_trans_1 (X : type) (x : term X) (y : term X) (z : term X)
                (P : z : term X -> Eq X y z -> type)
                (h : Eq X x y) (h' : Eq X y z)
                (p : term (P x (sym X x y h))) :
                term (P z h') :=
  bpi X y z h' (z : term X => h' : Eq X y z => P z h')
     (bpi X x y h
          (z : term X => h'' : Eq X x z => P z (trans X y x z (sym X x y h) h''))
          p).

(; The right-hand side ;)

def bpi_trans_2 (X : type) (x : term X) (y : term X) (z : term X)
                (P : z : term X -> Eq X y z -> type)
                (h : Eq X x y) (h' : Eq X y z)
                (p : term (P x (sym X x y h))) : term (P z h') :=
  bpi X x z (trans X x y z h h')
    (z : term X => h'' : Eq X x z => P z (trans X y x z (sym X x y h) h'')) p.

(; The following rule is rejected ;)

[X,x,y,z,P,h,h',p]
  bpi X y z h' P
     (bpi X x y h
          (z => h'' => P z (trans X y x z (sym X x y h) h''))
          p)
    -->
  bpi X x z (trans X x y z h h')
    (z : term X => h'' : Eq X x z => P z (trans X y x z (sym X x y h) h'')) p.

(; [dedukti66.dk, 46:0-53:77] Error on command.
Rule [bpi ?X ?y ?z ?h' ?P (bpi ?X ?x ?y ?h (z:?#0 => h'':?#1[z] => ?P z (trans ?X ?y ?x z (sym ?X ?x ?y ?h) h'')) ?p)
  → bpi <?X> <?x> <?z> (trans <?X> <?x> <?y> <?z> <?h> <?h'>) (z:term <?X> => h'':Eq <?X> <?x> z => <?P> z (trans <?X> <?y> <?x> z (sym <?X> <?x> <?y> <?h>) h'')) <?p>] does not preserve typing. ;)
```

**Comment by fblanqui** [comment]
Moreover, the error message has two problems:
1. It is wrong. In case of failure, we should not say "l-->r does not preserve typing" but "we cannot prove that l-->r preserves typing".
2. It gives no hint on why it didn't succeed (what are the constraints it couldn't solve?).

**Comment by rlepigre** [comment]
Is this example minimal?

**Comment by fblanqui** [comment]
The error message is now (thanks Rodolphe):

[65.dk, 46:0-53:77] Error on command.
Cannot solve [(z:term ?X => h'':Eq ?X ?x z => ?P z (trans ?X ?y ?x z (sym ?X ?x ?y ?h) h'')) ?z (trans ?X ?x ?y ?z ?h ?h')] ~ [?P ?z ?h']
Unable to prove SR for rule [bpi ?X ?y ?z ?h' ?P (bpi ?X ?x ?y ?h (z:?#0 => h'':?#1[z] => ?P z (trans ?X ?y ?x z (sym ?X ?x ?y ?h) h'')) ?p) → bpi <?X> <?x> <?z> (trans <?X> <?x> <?y> <?z> <?h> <?h'>) (z:term <?X> => h'':Eq <?X> <?x> z => <?P> z (trans <?X> <?y> <?x> z (sym <?X> <?x> <?y> <?h>) h'')) <?p>].

So, after beta-reduction, it cannot prove that ?P ?z (trans ?X ?y ?x ?z (sym ?X ?x ?y ?h) (trans ?X ?x ?y ?z ?h ?h')) ~ ?P ?z ?h'. Indeed, it cannot apply rule [A,a,b,h] trans A b a b (sym A a b h) h --> refl A b because ?y <> ?z.

The only constraint generated by typing the LHS is:
[subj] LHS has type [term (?P ?z ?h')]
[subj]   if [(z:term ?X => h'':Eq ?X ?x z => ?P z (trans ?X ?y ?x z (sym ?X ?x ?y ?h) h'')) ?y ?h] = [?P ?y (refl ?X ?y)]

After beta-reduction, it is ?P ?y (trans ?X ?y ?x ?y (sym ?X ?x ?y ?h) ?h) ~ ?P ?y (refl ?X ?y), which is satisfied if we apply the above rule. So, this constraint should not be generated.

But this does not explain whether there is something wrong with this example or not.

**Comment by rlepigre** [comment]
I personally find this example very hard to understand. There are too many variables !

Does this mean that we should apply `Eval.snf` somewhere in constraints?

**Comment by fblanqui** [comment]
Yes, it is complicated to analyze! I'm trying to understand it too. Concerning the constraint mentioned above, we could remove it if I'm not wrong. Currently, we remove constraints (l,r) such that l and r est syntactically equal. We should probably remove constraints (l,r) such that l and r have the same normal form too. It should be easy to do.

**Comment by fblanqui** [comment]
Here is my analysis of the LHS. I hope I made no mistake:

bpi : A : type -> a : term A -> b : term A -> ab : Eq A a b ->
          P : (c : term A -> Eq A a c -> type) ->
          term (P a (refl A a)) -> term (P b ab).

LHS = bpi A y z yz P l1
l1 = bpi A x y xy l2 p
l2 = \c \xc l3
l3 = P c (trans A y x c (sym A x y xy) xc)

variables A:_A, y:_y, z:_z, yz:_yz, P:_P, x:_x, xy:_xy, p:_p, c:_c, xc:_xc

If LHS is typable, then LHS : term (P z yz)

A : type? => _A = type
y : term A? => _y = term A
z : term A? => _z = term A
yz : Eq A y z?
  A:type? ok
  y:term A? ok
  z:term A? ok
P : c: term A -> Eq A y c -> type? => _P = c: term A -> Eq A y c -> type
l1 : term (P y (refl A y))?
    A:type? ok
    x:term A? => _x = term A
    y:term A? ok
    xy:Eq A x y? => _xy = Eq A x y
    l2:  c: term A -> Eq A x c -> type? => _c = term A, _xc=Eq A x c
        l3:type?
            c:term A? ok
            trans A y x c (sym A x y xy) xc : Eq A y c? ok
    p:term (P x (refl A x))? => _p = term (P x (refl A x))

It seems that the LHS is typable whatever the values of y and z are.

**Comment by fblanqui** [comment]
Here is the file with variables renamed.

[65.dk.txt](https://github.com/rlepigre/lambdapi/files/2360770/65.dk.txt)

**Comment by fblanqui** [comment]
I'm first trying to analyze the typability of the LHS:

bpi : A : type -> a : term A -> b : term A -> ab : Eq A a b ->
          P : (c : term A -> Eq A a c -> type) ->
          term (P a (refl A a)) -> term (P b ab).

LHS = bpi A y z yz P l1
l1 = bpi A x y xy l2 p
l2 = \c \xc l3
l3 = P c (trans A y x c (sym A x y xy) xc)

variables A:_A, y:_y, z:_z, yz:_yz, P:_P, x:_x, xy:_xy, p:_p, c:_c, xc:_xc

If LHS is typable, then LHS : term (P z yz)
A : type? => _A = type
y : term A? => _y = term A
z : term A? => _z = term A
yz : Eq A y z?
-  A:type? ok
-  y:term A? ok
-  z:term A? ok
P : c: term A -> Eq A y c -> type? => _P = c: term A -> Eq A y c -> type
l1 : term (P y (refl A y))?
- if l1 is typable, then l1 : term (P y xy) => term (P y (refl A y)) ~?~ term (P y xy)
- A:type? ok
- x:term A? => _x = term A
- y:term A? ok
- xy:Eq A x y? => _xy = Eq A x y
- l2:  c: term A -> Eq A x c -> type? => _c = term A, _xc=Eq A x c
   - l3:type?
       - c:term A? ok
       - trans A y x c (sym A x y xy) xc : Eq A y c? ok
- p:term (P x (refl A x))? => _p = term (P x (refl A x))

Hence, LHS is typable if term (P y (refl A y)) ~ term (P y xy).

This is not the constraint that we get. Did I make a mistake?

**Comment by rafoo** [comment]
> Is this example minimal?

Probably not.

> I personally find this example very hard to understand.

I can explain the motivations if that helps.

My goal was to extend Observational Type Theory (which is easy to encode in Dedukti, see https://github.com/Deducteam/Libraries/blob/master/theories/ott.dk) to the univalence axiom. `eq` is the equality relation, `refl`, `sym`, and `trans` represent respectively the reflexivity, symmetry, and transitivity principles for equality and `bpi` stands for "based-path induction" which is one possible way of stating the induction principle for equality. As in OTT, I wanted to define equality by induction on its type argument so for example `eq (A × B) ab ab'` is defined by `(eq A (fst ab) (fst ab')) × (eq B (snd ab) (snd ab'))`. For technical reasons, we need to define a whole bunch of functions related to equality mutually and `bpi` is one of them.

The problematic rewrite rule is the dependent version of  the commutation of `transport` and `trans`:

```
type : Type.
def term : type -> Type.

eq : A : type -> term A -> term A -> type.
def Eq (A : type) (a : term A) (b : term A) : Type := term (eq A a b).

refl : A : type -> a : term A -> Eq A a a.
sym : A : type -> a : term A -> b : term A -> Eq A a b -> Eq A b a.
def trans : A : type -> a : term A -> b : term A -> c : term A ->
            Eq A a b -> Eq A b c -> Eq A a c.

def transport : X : type -> x : term X -> y : term X -> h : Eq X x y ->
                P : (y : term X -> type) -> term (P x) -> term (P y).

[X,x,y,z,P,h,h',p]
  transport X y z h' (z => P z)
     (transport X x y h (z => P z) p)
    -->
  transport X x z (trans X x y z h h') (z : term X => P z) p.
```
