### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/lambdapi#71]
On the following example, there is a mistake on the type of the `D` function

```
Nat : Type.

0 : Nat.

def D : Nat -> Nat -> Nat.

[] D 0 --> 0.

S : Nat -> Nat.
```

I wrote `Nat -> Nat -> Nat` instead of `Nat -> Nat`. However, the error message given by `lambdapi` is not really explicit

```
[foo.dk, 14:0-12] Error on command.
Unable to prove SR for rule [D 0 → 0].
```

For this rather simple function, it is quite easy to debug. However, I suspect for more complex rewrite rules, that kind of error message is too vague to help the user. Is it possible to enhance the error message here?

**Comment by fblanqui** [comment]
But this is a bug: this rule should be rejected since it does not preserves typing. The LHS has type Nat->Nat while the RHS has type Nat. The constraint Nat ~ Nat->Nat is not satisfiable (in the current environment).

**Comment by fblanqui** [comment]
Anyway, in case of failure while trying to prove SR, Lambdapi should output the unsolved constraints even if the flag --debug j is not set.

**Comment by francoisthire** [comment]
Why is this a bug? The rule should be rejected and is indeed rejected.

**Comment by rlepigre** [comment]
> But this is a bug: this rule should be rejected since it does not preserves typing. The LHS has type Nat->Nat while the RHS has type Nat. The constraint Nat ~ Nat->Nat is not satisfiable (in the current environment).

Well, the rule is rejected. This is not a bug.

**Comment by rlepigre** [comment]
>Anyway, in case of failure while trying to prove SR, Lambdapi should output the unsolved constraints even if the flag --debug j is not set.

I'm not going to do that right now, because this requires some refactoring in `src/solve.ml`.

**Comment by fblanqui** [comment]
In this case, Lambdapi could even say that SR is broken.
