### ISSUE TITLE
Use Unix.create_process instead of Unix.fork (not implemented on Windows)

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#9]
https://github.com/rlepigre/lambdapi/blob/7a256a6916501a9e9b9d0a9eb93194c258c31e62/sign.ml#L162

**Comment by fblanqui** [comment]
No. But this is important to add a remark about that and mention it in 
the README too.


Le 25/01/2018 à 13:12, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
OK, I'll do that and close the issue then.

**Comment by craff** [comment]
On 18-01-25 12:25:07, Rodolphe Lepigre wrote:
> Closed #9.

With cygwin, fork is provided for windows ... One should try a cygwin build ?

**Comment by rlepigre** [comment]
Yes, I mentioned it in the README. I don't think we should bother trying ourselves. Moreover, I am working on an online version (compiled with `js_of_ocaml`) for people to try the system without having to install it.
